description: >
  Single Docker container used to run Cypress Tests
parameters:
  node-version:
    type: string
    default: "22.15.0" # keep in sync with jobs/run.yml
    description: >
      The version of Node to run your tests with.
docker:
  - image: cimg/node:<< parameters.node-version >>-browsers
