description: >
  Run Cypress tests using the cypress/default executor with a specified node version.
usage:
  version: 2.1
  orbs:
    cypress: cypress-io/cypress@3
jobs:
  run-cypress-in-specified-node-version:
    executor:
      name: cypress/default
      node-version: "20.6"
    steps:
      - cypress/install:
          package-manager: "yarn"
      - cypress/run-tests:
          start-command: "npm run start:dev"
          cypress-command: "npx cypress run"
workflows:
  use-my-orb:
    jobs:
      - run-cypress-in-specified-node-version:
          name: Run Cypress in Node 20
